# Generated by Django 5.1.1 on 2024-09-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20190502_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='expertize',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='service',
            name='items',
        ),
        migrations.DeleteModel(
            name='Expertize',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
